-- PostgreSQL staging schema draft.
-- Runtime still defaults to SQLite; apply this only to a separate PostgreSQL test database.

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  password_hash TEXT,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL,
  allowed_stations TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id TEXT NOT NULL UNIQUE,
  cleancloud_order_id TEXT NOT NULL UNIQUE,
  customer_name TEXT NOT NULL,
  customer_id TEXT,
  order_weight REAL,
  customer_phone TEXT,
  customer_email TEXT,
  service_tier TEXT NOT NULL,
  status TEXT NOT NULL,
  cleancloud_status TEXT NOT NULL,
  ready_to_place INTEGER NOT NULL DEFAULT 0,
  ready_for_pickup INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS baskets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id),
  basket_code TEXT NOT NULL UNIQUE,
  basket_type TEXT NOT NULL,
  basket_items_json TEXT,
  basket_kind TEXT NOT NULL DEFAULT 'main',
  parent_basket_id INTEGER REFERENCES baskets(id),
  rework_reason TEXT,
  rework_attempt INTEGER NOT NULL DEFAULT 0,
  station TEXT NOT NULL,
  status TEXT NOT NULL,
  qr_code TEXT NOT NULL UNIQUE,
  label_printed_at TEXT,
  label_print_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS basket_catalog (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL UNIQUE,
  qr_code TEXT NOT NULL UNIQUE,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pickup_locations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL UNIQUE,
  qr_code TEXT NOT NULL UNIQUE,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pickup_order_placements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id),
  slot_index INTEGER NOT NULL,
  bin_qr_code TEXT NOT NULL,
  location_qr_code TEXT NOT NULL,
  placed_by TEXT NOT NULL,
  placed_at TEXT NOT NULL,
  released_by TEXT,
  released_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS laundry_machines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_code TEXT NOT NULL UNIQUE,
  station TEXT NOT NULL,
  machine_type TEXT NOT NULL,
  display_name TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS machine_loads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  machine_id INTEGER NOT NULL REFERENCES laundry_machines(id),
  station TEXT NOT NULL,
  status TEXT NOT NULL,
  started_by TEXT NOT NULL,
  started_at TEXT NOT NULL,
  completed_by TEXT,
  completed_at TEXT,
  cancelled_by TEXT,
  cancelled_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS machine_load_baskets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  load_id INTEGER NOT NULL REFERENCES machine_loads(id),
  basket_id INTEGER NOT NULL REFERENCES baskets(id),
  order_id INTEGER NOT NULL REFERENCES orders(id),
  added_at TEXT NOT NULL,
  unloaded_at TEXT,
  unloaded_by TEXT,
  UNIQUE(load_id, basket_id)
);

CREATE TABLE IF NOT EXISTS rework_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id),
  source_basket_id INTEGER NOT NULL REFERENCES baskets(id),
  rework_basket_id INTEGER REFERENCES baskets(id),
  item_category TEXT NOT NULL,
  item_label TEXT,
  quantity INTEGER NOT NULL DEFAULT 1,
  source_image_id INTEGER,
  source_image_url TEXT,
  source_image_note TEXT,
  qc_photo_path TEXT,
  qc_photo_url TEXT,
  reason_code TEXT NOT NULL,
  service_label TEXT NOT NULL,
  extra_days INTEGER NOT NULL DEFAULT 1,
  request_status TEXT NOT NULL,
  requested_by TEXT NOT NULL,
  requested_at TEXT NOT NULL,
  decision_actor TEXT,
  decision_at TEXT,
  decision_note TEXT,
  handoff_confirmed_by TEXT,
  handoff_confirmed_at TEXT,
  handoff_note TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS scan_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id),
  basket_id INTEGER REFERENCES baskets(id),
  station TEXT NOT NULL,
  actor TEXT NOT NULL,
  result TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS basket_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basket_id INTEGER NOT NULL REFERENCES baskets(id),
  image_role TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  note TEXT,
  file_path TEXT NOT NULL,
  public_url TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_queue (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id),
  action TEXT NOT NULL,
  payload TEXT NOT NULL,
  status TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TEXT NOT NULL,
  processed_at TEXT
);

CREATE TABLE IF NOT EXISTS idempotency_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idem_key TEXT NOT NULL,
  route_key TEXT NOT NULL,
  actor TEXT NOT NULL,
  status_code INTEGER NOT NULL,
  response_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  UNIQUE(idem_key, route_key, actor)
);

CREATE TABLE IF NOT EXISTS webhook_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,
  event_key TEXT NOT NULL UNIQUE,
  payload TEXT NOT NULL,
  status TEXT NOT NULL,
  message TEXT NOT NULL,
  received_at TEXT NOT NULL,
  processed_at TEXT
);

CREATE TABLE IF NOT EXISTS security_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  actor TEXT NOT NULL,
  ip TEXT NOT NULL,
  path TEXT NOT NULL,
  method TEXT NOT NULL,
  status INTEGER NOT NULL,
  message TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_baskets_order_id ON baskets(order_id);
CREATE INDEX IF NOT EXISTS idx_baskets_station_status ON baskets(station, status);
CREATE INDEX IF NOT EXISTS idx_scan_events_order_id ON scan_events(order_id);
CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON sync_queue(status);
